Move implemetation of some MusRC stuff out of the header file.
This is so that the tests compile and link on linux - I was getting some
undefined reference to ToRendererX and ToRendererY, even though the 
methods were implemented in the header file. Moving the stubs out into
fakemus compiles and links fine